[package]
name = "mcsapp-motion-tracker"
version = "0.1.0"
authors = ["Aditya Kresna <aditya.kresna@outlook.co.id>"]
edition = "2018"

[dependencies]
mimalloc = { version = "0.1.11", default-features = false }
