name: AVS MCS Suite Build

on:
  push:
    branches:
      - master
      - develop
      - release/*

jobs:
  complete_tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - uses: actions/checkout@v1
      - name: Pre-requisites (Make)
        run: sudo apt-get install make
      - name: OpenCV Build
        run: make prepare
      - name: Build
        run: make build
      - name: Linter
        run: make lint
      - name: Unit and Integration Tests
        run: make test
